Add new dotfiles; update 'install'
.bash_profile and .profile have been added.
Considering .bashrc is meant for more of an interactive
non-login bash session, I chose to follow this convention
and keep it so.

'install' has been edited to work with '.profile'.
This is mainly to follow suit from above, but also
that interactive login sessions should be able to also
have access to the same env vars currently.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,16 +4,18 @@
 set -e
 PWD="$(pwd)"
 PROGRAM_NAME="install"
-BASHRC_FILE_NAME=".bashrc" # assuming .bashrc is ALWAYS '.bashrc'
+PROFILE_FILE_NAME=".profile" # assuming .profile is ALWAYS '.profile'
 TEMP_DIR_NAME="${PROGRAM_NAME}-temp"
-BASHRC_REMOTE_URL='https://raw.githubusercontent.com/reap2sow1/dotfiles/main/.bashrc'
+PROFILE_REMOTE_URL='https://raw.githubusercontent.com/reap2sow1/dotfiles/main/.profile'
 DOTFILES_TO_INCLUDE_FOR_LINKING=(
     .bashrc
+    .profile
+    .bash_profile
 )
 
 if [ "$PWD" != "$HOME" ]; then
-    # main reason is to avoid filemode permissions
-    echo "${PROGRAM_NAME}: Re-run this script in $HOME (assuming you haven't changed this!), to run this correctly"
+    # main reason is to avoid filemode permissions issues
+    echo "${PROGRAM_NAME}: re-run this script in $HOME (assuming you haven't changed this!), to run this correctly"
     exit 1
 fi
 
@@ -28,19 +30,22 @@ if [ -z "$(which wget)" ]; then
     exit 1
 fi
 
-if ! wget --quiet "$BASHRC_REMOTE_URL"; then
-    echo "${PROGRAM_NAME}: Could not fetch .bashrc from url!"
+if ! wget --quiet "$PROFILE_REMOTE_URL"; then
+    echo "${PROGRAM_NAME}: could not fetch .profile from url!"
     exit 1
 fi
 
 # shellcheck disable=SC1090
-source "./${BASHRC_FILE_NAME}"
-rm "./${BASHRC_FILE_NAME}"
+source "./${PROFILE_FILE_NAME}"
+rm "./${PROFILE_FILE_NAME}"
 cd ..
 rmdir "$TEMP_DIR_NAME"
 
-if ! [ -d "$GIT_REPOS_PATH" ]; then 
-    mkdir "$GIT_REPOS_PATH"
+if [ -z "$GIT_REPOS_PATH" ]; then
+    echo "${PROGRAM_NAME}: unable to import env vars from .profile"
+    exit 1
+elif ! [ -d "$GIT_REPOS_PATH" ]; then 
+    mkdir -p "$GIT_REPOS_PATH"
 fi
 
 LOCAL_REPO_PATH="${GIT_REPOS_PATH}/${DOTFILES_REPO_NAME}"
@@ -48,7 +53,7 @@ LOCAL_REPO_PATH="${GIT_REPOS_PATH}/${DOTFILES_REPO_NAME}"
 # using parameter expansion, ',,' append will convert the string to lowercase
 if [ "${RE_INSTALL_REPLY,,}" == "y" ]; then
     if ! [ -d "$LOCAL_REPO_PATH" ]; then
-        echo "$ERROR the $DOTFILES_REPO_NAME cannot be found, its possible remote $BASHRC_FILE_NAME has changed recently"
+        echo "$ERROR the $DOTFILES_REPO_NAME cannot be found on the local file system"
         exit 1
     fi
     rm -rf "$LOCAL_REPO_PATH"
